### PR TITLE
Resolving addresses to symbolic names

### PR DESCRIPTION
**Pull request by dstogov**

### CODE REVIEW

**Comment by asveikau** [comment]
I found this functionality useful, too, but I had some comments on the approach.  First there's no pointer back to the u struct given to the callback, so it's hard to do stuff without using global variables.  Second, mkasm() doesn't check for overflow, so the resolver can't return a long string.  I created a new fork which addresses these.

**Comment by dstogov** [comment]
Thanks, for information.
I didn't look into the code, but I according to comments your changes make
sense.

Thanks. Dmitry.

**Comment by vmt** [comment]
Dimitry, first apologies for taking so long to close on this. I had to wade through a lot of pending changes which I pushed in the past week. I like your idea, and based on Andrew's changes in his fork, I have come up with something that I hope is useful but still simple.

I have fixed the overflow issue, but I did not want to introduce buffer resizing into the api. So what's I've done is increase the internal buffer size to 120 which should cover the common case. For the uncommon case I have added an interface that allows the client to specify a statically sized buffer. In both cases the semantics remain the same; the output is truncated on overflow. I think this is a reasonable approach that should work for all cases.

I have gone a step further with the callback, and added support for both symbol and an offset. For example, take a look at the test output $(src)/tests/test_sym_resolver.ref.

Again, thank you for taking the time to let me know about your ideas and for this patch. I am closing this request. Hope to see more comments and contributions from all.

**Comment by asveikau** [comment]
Looks like a decent set of diffs, Vivek.  I can see why you left out the resizer; I struggled with it myself especially given that there are no dynamic buffers in the ud struct.  I just figured it would be fair to let the callback make the ultimate decision about whether to truncate; if no callback is present you're not really paying much, and if the callback allocates the caller a few frames up would be on its own to free it, without overcomplicating the library.  But I do think the choices you've made are reasonable.

**Comment by vmt** [comment]
I had similar ideas as well, somehow punting everything to the client. The problem with that is it starts to look like the symbol resolver is overloading for the what is a deficiency in the overall output buffering mechanism. Taking a step back, I feel now that the api for assembly output is poorly designed. Moving the buffer to the client makes ud_insn_asm look awkward. Having said all that, I am thinking addressing this has marginal returns. I am not convinced that users will see truncations with the default or a user assigned reasonably sized static buffer. Let me know how this works out for you. Thanks!

**Pull request closed without merging**
